import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, Check, ChevronDown, FileCheck2, Menu, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ContactForm } from '../components/ContactForm'
import { Logo } from '../components/Logo'
import { ProgressRing } from '../components/ProgressRing'
import { ThemeToggle } from '../components/ThemeToggle'
import { faqs, features } from '../data/site'

const fade = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .2 }, transition: { duration: .55 } }

function Navbar() {
  const [open, setOpen] = useState(false)
  const links = [['Features', '#features'], ['How it works', '#how'], ['Pricing', '#pricing'], ['FAQ', '#faq'], ['Contact', '#contact']]
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/75 backdrop-blur-xl dark:border-white/10 dark:bg-[#080b13]/75">
    <div className="container-shell flex h-20 items-center gap-6"><Logo /><nav className="ml-8 hidden items-center gap-7 lg:flex">{links.map(([label, href]) => <a key={href} href={href} className="text-sm font-semibold text-slate-600 transition hover:text-blue-600 dark:text-slate-300 dark:hover:text-blue-400">{label}</a>)}</nav><div className="ml-auto flex items-center gap-3"><ThemeToggle /><Link to="/login" className="hidden rounded-xl px-3 py-2 text-sm font-semibold text-slate-700 hover:text-blue-600 dark:text-slate-200 sm:block">Sign in</Link><Link to="/register" className="button-primary hidden sm:inline-flex">Analyze resume <ArrowRight size={17} /></Link><button onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white lg:hidden dark:border-white/10 dark:bg-white/[.04]" aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></div></div>
    <AnimatePresence>{open && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="border-t border-slate-200 bg-white px-4 pb-5 dark:border-white/10 dark:bg-[#0b0f19] lg:hidden"><div className="container-shell flex flex-col gap-2 pt-3">{links.map(([label, href]) => <a key={href} href={href} onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-white/[.06]">{label}</a>)}<Link to="/register" className="button-primary mt-2">Start free analysis</Link></div></motion.div>}</AnimatePresence>
  </header>
}

function ProductPreview() {
  return <motion.div initial={{ opacity: 0, y: 30, rotateX: 4 }} animate={{ opacity: 1, y: 0, rotateX: 0 }} transition={{ duration: .75, delay: .2 }} className="relative mx-auto mt-14 max-w-6xl px-3 sm:px-6">
    <div className="absolute -inset-8 -z-10 rounded-[3rem] bg-gradient-to-r from-blue-500/15 via-cyan-400/10 to-violet-500/15 blur-3xl" />
    <div className="overflow-hidden rounded-[2rem] border border-white/80 bg-white/85 shadow-[0_40px_120px_-40px_rgba(15,23,42,.45)] backdrop-blur-xl dark:border-white/10 dark:bg-[#0d1320]/90">
      <div className="flex h-12 items-center gap-2 border-b border-slate-200 px-5 dark:border-white/10"><span className="h-2.5 w-2.5 rounded-full bg-rose-400" /><span className="h-2.5 w-2.5 rounded-full bg-amber-400" /><span className="h-2.5 w-2.5 rounded-full bg-emerald-400" /><div className="mx-auto h-7 w-52 rounded-lg bg-slate-100 text-center text-[10px] leading-7 text-slate-400 dark:bg-white/[.05]">app.smartresume.ai/results</div></div>
      <div className="grid lg:grid-cols-[210px_1fr]"><div className="hidden border-r border-slate-200 p-5 dark:border-white/10 lg:block"><Logo compact /><div className="mt-8 space-y-2">{['Overview', 'New analysis', 'Resume history', 'Career insights'].map((item, i) => <div key={item} className={`rounded-xl px-3 py-2.5 text-xs font-semibold ${i === 1 ? 'bg-blue-600 text-white' : 'text-slate-400'}`}>{item}</div>)}</div></div><div className="p-4 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Analysis complete</p><h3 className="mt-1 font-display text-xl font-bold sm:text-2xl">Your strongest career direction</h3></div><span className="hidden rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 sm:block dark:bg-emerald-500/10 dark:text-emerald-300">Ready to improve</span></div><div className="grid gap-4 md:grid-cols-[1.25fr_.75fr]"><div className="rounded-3xl bg-gradient-to-br from-blue-600 to-violet-700 p-5 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-blue-100">Top classification</p><h4 className="mt-1 font-display text-2xl font-extrabold">Backend Developer</h4><p className="mt-3 max-w-md text-xs leading-5 text-blue-100">Evidence from Python, FastAPI, PostgreSQL, REST API, Docker, and authentication.</p></div><FileCheck2 className="opacity-70" /></div><div className="mt-5 space-y-3">{[['Backend Developer', 42], ['Software Engineer', 29], ['Cloud Engineer', 13]].map(([name, value]) => <div key={name as string}><div className="mb-1 flex justify-between text-[10px] font-semibold"><span>{name}</span><span>{value}%</span></div><div className="h-1.5 rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{ width: `${value}%` }} /></div></div>)}</div></div><div className="card flex items-center justify-center p-4"><ProgressRing value={78} size={142} label="ATS" /></div></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><p className="text-xs text-slate-400">Skills detected</p><p className="mt-1 font-display text-2xl font-bold">12</p></div><div className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><p className="text-xs text-slate-400">High-priority gaps</p><p className="mt-1 font-display text-2xl font-bold">3</p></div><div className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><p className="text-xs text-slate-400">JD match</p><p className="mt-1 font-display text-2xl font-bold">74%</p></div></div></div></div>
    </div>
  </motion.div>
}

export function LandingPage() {
  const [faq, setFaq] = useState<number | null>(0)
  return <div className="app-shell overflow-hidden"><Navbar />
    <main>
      <section className="mesh-bg relative overflow-hidden pb-24 pt-36 sm:pt-44"><div className="grid-mask pointer-events-none absolute inset-0" /><div className="container-shell relative text-center"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="eyebrow"><Sparkles size={13} /> Career intelligence for every resume</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="mx-auto mt-7 max-w-5xl font-display text-4xl font-extrabold leading-[1.05] tracking-[-.045em] sm:text-6xl lg:text-7xl">Know where your resume fits.<br /><span className="text-gradient">Know exactly what to improve.</span></motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15 }} className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300 sm:text-lg">Classify your strongest career domains, measure ATS readiness, compare against a job description, and turn missing skills into a practical roadmap.</motion.p><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .22 }} className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><Link to="/register" className="button-primary w-full sm:w-auto">Analyze my resume <ArrowRight size={18} /></Link><a href="#how" className="button-secondary w-full sm:w-auto"><Zap size={17} /> See how it works</a></motion.div><div className="mt-7 flex flex-wrap justify-center gap-x-6 gap-y-2 text-xs font-medium text-slate-500"><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-emerald-500" /> No credit card</span><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-emerald-500" /> PDF, DOCX, TXT</span><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-emerald-500" /> Transparent deductions</span></div></div><ProductPreview /></section>

      <section className="border-y border-slate-200 bg-white py-7 dark:border-white/10 dark:bg-white/[.02]"><div className="container-shell grid grid-cols-2 gap-6 text-center md:grid-cols-4">{[['16', 'career taxonomies'], ['8', 'ATS score dimensions'], ['5', 'ranked predictions'], ['3', 'free analyses/month']].map(([value, label]) => <div key={label}><p className="font-display text-3xl font-extrabold text-gradient">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.12em] text-slate-400">{label}</p></div>)}</div></section>

      <section id="features" className="py-24 sm:py-32"><div className="container-shell"><motion.div {...fade} className="mx-auto max-w-2xl text-center"><span className="eyebrow">One clear workflow</span><h2 className="mt-5 font-display text-3xl font-extrabold tracking-tight sm:text-5xl">More than a score. A career decision system.</h2><p className="mt-5 leading-7 text-slate-500">Every feature supports the core classification result, so users understand not just what was predicted, but what evidence is missing.</p></motion.div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, text }, index) => <motion.article {...fade} transition={{ duration: .45, delay: index * .04 }} key={title} className="card group transition hover:-translate-y-1 hover:border-blue-200 dark:hover:border-blue-500/30"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-600 transition group-hover:bg-blue-600 group-hover:text-white dark:bg-blue-500/10 dark:text-blue-300"><Icon size={20} /></span><h3 className="mt-5 font-display text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p></motion.article>)}</div></div></section>

      <section id="how" className="bg-slate-950 py-24 text-white sm:py-32"><div className="container-shell"><motion.div {...fade} className="max-w-2xl"><span className="eyebrow border-white/10 bg-white/5 text-blue-300">How it works</span><h2 className="mt-5 font-display text-3xl font-extrabold sm:text-5xl">From upload to next action in four focused steps.</h2></motion.div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[
        ['01', 'Upload securely', 'Add a PDF, DOCX, or TXT resume. The parser extracts readable text and checks contact details and sections.'],
        ['02', 'Set your direction', 'Choose a target role, experience level, and optionally paste a real job description.'],
        ['03', 'Analyze evidence', 'The engine ranks career domains, scores ATS readiness, and measures job-description alignment.'],
        ['04', 'Act on the gaps', 'Review missing skills, bullet improvements, interview questions, and export a professional report.'],
      ].map(([number, title, text]) => <motion.div {...fade} key={number} className="rounded-3xl border border-white/10 bg-white/[.045] p-6"><span className="font-display text-4xl font-extrabold text-blue-400/50">{number}</span><h3 className="mt-5 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></motion.div>)}</div></div></section>

      <section id="pricing" className="py-24 sm:py-32"><div className="container-shell"><motion.div {...fade} className="mx-auto max-w-2xl text-center"><span className="eyebrow">Simple pricing</span><h2 className="mt-5 font-display text-3xl font-extrabold sm:text-5xl">Start free. Upgrade when the workflow becomes essential.</h2></motion.div><div className="mx-auto mt-14 grid max-w-6xl gap-5 lg:grid-cols-3">{[
        { name: 'Free', price: '$0', text: 'For testing the workflow', features: ['3 analyses each month', 'Top-5 career classification', 'Core ATS analysis', 'Basic skill gaps'], cta: 'Start free' },
        { name: 'Pro', price: '$12', text: 'For active job seekers', features: ['Unlimited analyses', 'Advanced JD matching', 'AI-assisted rewriting', 'Interview preparation', 'PDF report history'], cta: 'Choose Pro', popular: true },
        { name: 'Recruiter', price: '$49', text: 'For small hiring teams', features: ['Bulk resume ingestion', 'Candidate ranking', 'Search and filters', 'Team workspace', 'CSV exports'], cta: 'Join waitlist' },
      ].map((plan) => <motion.div {...fade} key={plan.name} className={`relative rounded-[2rem] border p-7 shadow-soft ${plan.popular ? 'border-blue-500 bg-slate-950 text-white lg:-translate-y-4' : 'border-slate-200 bg-white dark:border-white/10 dark:bg-white/[.04]'}`}>{plan.popular && <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-blue-500 px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-white">Most popular</span>}<h3 className="font-display text-xl font-bold">{plan.name}</h3><p className={`mt-2 text-sm ${plan.popular ? 'text-slate-400' : 'text-slate-500'}`}>{plan.text}</p><div className="mt-6 flex items-end gap-2"><span className="font-display text-4xl font-extrabold">{plan.price}</span><span className={`pb-1 text-sm ${plan.popular ? 'text-slate-400' : 'text-slate-500'}`}>/month</span></div><ul className="mt-7 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-3 text-sm"><Check size={17} className="mt-0.5 shrink-0 text-emerald-500" />{feature}</li>)}</ul><Link to="/register" className={`mt-8 w-full ${plan.popular ? 'button-primary' : 'button-secondary'}`}>{plan.cta}</Link></motion.div>)}</div><p className="mt-6 text-center text-xs text-slate-400">Pricing is configuration-ready; connect a payment provider before accepting real subscriptions.</p></div></section>

      <section id="faq" className="border-y border-slate-200 bg-white py-24 dark:border-white/10 dark:bg-white/[.02] sm:py-32"><div className="container-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><motion.div {...fade}><span className="eyebrow">Clear answers</span><h2 className="mt-5 font-display text-3xl font-extrabold sm:text-5xl">Trust begins with honest limitations.</h2><p className="mt-5 leading-7 text-slate-500">The product explains deductions and avoids claiming certainty where representative evaluation data is required.</p></motion.div><div className="space-y-3">{faqs.map(([question, answer], index) => <motion.div {...fade} key={question} className="overflow-hidden rounded-2xl border border-slate-200 dark:border-white/10"><button onClick={() => setFaq(faq === index ? null : index)} className="flex w-full items-center justify-between gap-4 bg-white px-5 py-5 text-left font-display font-bold dark:bg-white/[.03]">{question}<ChevronDown size={18} className={`shrink-0 transition ${faq === index ? 'rotate-180' : ''}`} /></button><AnimatePresence>{faq === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p className="border-t border-slate-200 px-5 py-5 text-sm leading-6 text-slate-500 dark:border-white/10">{answer}</p></motion.div>}</AnimatePresence></motion.div>)}</div></div></section>

      <section id="contact" className="py-24 sm:py-32"><div className="container-shell grid items-start gap-10 lg:grid-cols-[.8fr_1.2fr]"><motion.div {...fade}><span className="eyebrow">Contact</span><h2 className="mt-5 font-display text-3xl font-extrabold sm:text-5xl">Questions, feedback, or an institutional use case?</h2><p className="mt-5 max-w-xl leading-7 text-slate-500">Send a message directly into the admin feedback queue. For public deployment, add rate limiting and a transactional support workflow.</p><div className="mt-7 space-y-3 text-sm font-semibold text-slate-600 dark:text-slate-300"><p className="flex items-center gap-3"><Check size={17} className="text-emerald-500" /> Product feedback and bug reports</p><p className="flex items-center gap-3"><Check size={17} className="text-emerald-500" /> University and recruiter enquiries</p><p className="flex items-center gap-3"><Check size={17} className="text-emerald-500" /> Privacy and data-retention questions</p></div></motion.div><motion.div {...fade}><ContactForm /></motion.div></div></section>

      <section className="py-24 sm:py-32"><div className="container-shell"><motion.div {...fade} className="relative overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-blue-600 via-indigo-600 to-violet-700 px-6 py-16 text-center text-white shadow-glow sm:px-12"><div className="absolute inset-0 opacity-20 grid-mask" /><div className="relative"><ShieldCheck className="mx-auto" size={34} /><h2 className="mx-auto mt-5 max-w-3xl font-display text-3xl font-extrabold sm:text-5xl">Stop guessing why a resume is rejected.</h2><p className="mx-auto mt-5 max-w-xl text-blue-100">Use evidence, transparent scoring, and a practical improvement roadmap before your next application.</p><Link to="/register" className="mt-8 inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3.5 text-sm font-bold text-blue-700 transition hover:-translate-y-0.5">Start free analysis <ArrowRight size={18} /></Link></div></motion.div></div></section>
    </main>
    <footer className="border-t border-slate-200 py-10 dark:border-white/10"><div className="container-shell flex flex-col items-center justify-between gap-5 text-center sm:flex-row sm:text-left"><Logo /><p className="text-xs leading-5 text-slate-400">© 2026 Smart Resume Classification. AI-assisted guidance, not a hiring guarantee.</p><div className="flex gap-5 text-xs font-semibold text-slate-500"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></div></div></footer>
  </div>
}
